import Foundation

/// One logical server mutation. `operationID` is generated at the boundary
/// that creates the action and is retained by the durable queue for every
/// retry. It is never generated by the HTTP transport.
struct ServerLedgerMutationRequest: Codable, Equatable, Sendable {
    let operationID: UUID
    let scope: ServerLedgerMutationScope
    let expectedRevision: Int64
    let requestPayload: Data
    let kind: String
    let method: String
    let path: String?

    init(
        operationID: UUID = UUID(),
        scope: ServerLedgerMutationScope,
        expectedRevision: Int64,
        requestPayload: Data,
        kind: String = "ledger.mutation",
        method: String = "POST",
        path: String? = nil
    ) {
        let queued = ServerLedgerQueuedMutationEnvelope.decode(requestPayload)
        self.operationID = operationID
        self.scope = scope
        self.expectedRevision = expectedRevision
        self.requestPayload = requestPayload
        self.kind = kind == "ledger.mutation" ? (queued?.kind ?? kind) : kind
        self.method = method == "POST" ? (queued?.method ?? method) : method
        self.path = path ?? queued?.path
    }

    init(
        operationID: UUID = UUID(),
        scope: ServerLedgerMutationScope,
        expectedRevision: Int64,
        kind: String,
        method: String = "POST",
        path: String,
        body: Data
    ) {
        let payload = (try? ServerLedgerQueuedMutationEnvelope.encode(
            kind: kind,
            method: method,
            path: path,
            body: body
        )) ?? body
        self.init(
            operationID: operationID,
            scope: scope,
            expectedRevision: expectedRevision,
            requestPayload: payload,
            kind: kind,
            method: method,
            path: path
        )
    }

    var accountID: String { scope.accountID }
    var payload: Data { bodyPayload }
    var bodyPayload: Data { ServerLedgerQueuedMutationEnvelope.decode(requestPayload)?.body ?? requestPayload }
    var idempotencyKey: String { operationID.uuidString }
    var endpointPath: String? { path ?? ServerLedgerMutationRoute.defaultPath(for: self) }
}

enum ServerLedgerAPIClientError: LocalizedError, Equatable, Sendable {
    case notImplemented
    case invalidURL
    case invalidRequest
    case invalidResponse
    case unauthorized
    case offline
    case server(status: Int, code: String?)
    case contractVersionMismatch
    case snapshotScopeMismatch
    case staleRevision
    case revisionConflict(
        expectedRevision: Int64,
        currentRevision: Int64?,
        snapshot: ServerLedgerSnapshot?
    )
    case idempotencyKeyReused

    var errorDescription: String? {
        switch self {
        case .notImplemented: return "Server ledger transport is not configured"
        case .invalidURL: return "Invalid server ledger URL"
        case .invalidRequest: return "Invalid server ledger mutation request"
        case .invalidResponse: return "Invalid server ledger response"
        case .unauthorized: return "The server session is no longer authorized"
        case .offline: return "The server ledger is unavailable offline"
        case let .server(status, code): return code ?? "Server ledger request failed with status \(status)"
        case .contractVersionMismatch: return "The server ledger contract is not supported"
        case .snapshotScopeMismatch: return "The server returned a snapshot for another account or group"
        case .staleRevision: return "The server returned an older ledger revision"
        case .revisionConflict: return "The shared ledger changed; refresh before retrying"
        case .idempotencyKeyReused: return "The operation ID is already bound to another request"
        }
    }
}

/// Transport boundary for the server-authoritative ledger. The protocol is
/// intentionally small so deterministic test clients can exercise cache and
/// reconciliation behavior without a live network.
protocol ServerLedgerAPIClient: Sendable {
    func fetchSnapshot(for scope: ServerBackedLedgerScope) async throws -> ServerLedgerSnapshot
    func submit(_ request: ServerLedgerMutationRequest) async throws -> ServerLedgerSnapshot
}

struct UnconfiguredServerLedgerAPIClient: ServerLedgerAPIClient {
    init() {}

    func fetchSnapshot(for scope: ServerBackedLedgerScope) async throws -> ServerLedgerSnapshot {
        throw ServerLedgerAPIClientError.notImplemented
    }

    func submit(_ request: ServerLedgerMutationRequest) async throws -> ServerLedgerSnapshot {
        throw ServerLedgerAPIClientError.notImplemented
    }
}

/// URLSession implementation used by the mobile target. It speaks the
/// checked-in ledger-v2 routes and centralizes authentication and contract
/// headers for reads and writes.
final class URLSessionServerLedgerAPIClient: ServerLedgerAPIClient, @unchecked Sendable {
    let baseURL: URL
    private let session: URLSession
    private let tokenProvider: @Sendable () -> String?

    init(
        baseURL: URL,
        session: URLSession = .shared,
        tokenProvider: @escaping @Sendable () -> String?
    ) {
        self.baseURL = baseURL
        self.session = session
        self.tokenProvider = tokenProvider
    }

    static func live() -> URLSessionServerLedgerAPIClient {
        URLSessionServerLedgerAPIClient(
            baseURL: SettlementAPIConfiguration.baseURL,
            tokenProvider: { SettlementTokenStore.read() }
        )
    }

    func fetchSnapshot(for scope: ServerBackedLedgerScope) async throws -> ServerLedgerSnapshot {
        let groupID = Self.pathComponent(scope.groupID)
        let path = "/api/mobile/ledger/groups/\(groupID)"
        let (data, status) = try await perform(path: path, method: "GET", body: nil, request: nil)
        guard (200..<300).contains(status) else {
            throw try makeHTTPError(status: status, data: data, scope: scope, expectedRevision: nil)
        }
        do {
            return try ServerLedgerDocumentValidator.snapshot(from: data, scope: scope)
        } catch let error as ServerLedgerDTOError {
            if case .contractVersionMismatch = error {
                throw ServerLedgerAPIClientError.contractVersionMismatch
            }
            throw error
        }
    }

    func submit(_ request: ServerLedgerMutationRequest) async throws -> ServerLedgerSnapshot {
        guard let path = request.endpointPath, path.isEmpty == false else {
            throw ServerLedgerAPIClientError.invalidRequest
        }
        let body = request.bodyWithMetadata()
        let (data, status) = try await perform(
            path: path,
            method: request.method,
            body: body,
            request: request
        )
        let requestedScope: ServerBackedLedgerScope?
        if case let .serverBacked(accountID, groupID) = request.scope {
            requestedScope = ServerBackedLedgerScope(accountID: accountID, groupID: groupID)
        } else {
            requestedScope = nil
        }
        guard (200..<300).contains(status) else {
            throw try makeHTTPError(
                status: status,
                data: data,
                scope: requestedScope,
                expectedRevision: request.expectedRevision
            )
        }

        let responseObject = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any]
        if responseObject?["kind"] as? String == "mutation_result" {
            let result = try JSONDecoder.serverLedger.decode(ServerLedgerMutationResultDTO.self, from: data)
            guard result.contractVersion == ServerLedgerContract.version else {
                throw ServerLedgerAPIClientError.contractVersionMismatch
            }
            guard result.groupID.isEmpty == false,
                  result.groupID == requestedScope?.groupID || requestedScope == nil else {
                throw ServerLedgerAPIClientError.snapshotScopeMismatch
            }
            let canonicalScope = ServerBackedLedgerScope(
                accountID: request.accountID,
                groupID: result.groupID
            )
            let canonical = try await fetchSnapshot(for: canonicalScope)
            guard canonical.revision >= result.revision else {
                throw ServerLedgerAPIClientError.staleRevision
            }
            return canonical
        }

        let readModelData = Self.readModelData(from: data) ?? data
        let scope = requestedScope ?? Self.scope(from: readModelData, accountID: request.accountID)
        guard let scope else {
            throw ServerLedgerAPIClientError.snapshotScopeMismatch
        }
        do {
            return try ServerLedgerDocumentValidator.snapshot(
                from: readModelData,
                scope: scope,
                fallbackRevision: request.expectedRevision
            )
        } catch let error as ServerLedgerDTOError {
            if case .contractVersionMismatch = error {
                throw ServerLedgerAPIClientError.contractVersionMismatch
            }
            throw error
        }
    }

    private func perform(
        path: String,
        method: String,
        body: Data?,
        request mutation: ServerLedgerMutationRequest?
    ) async throws -> (Data, Int) {
        guard let url = URL(string: path, relativeTo: baseURL)?.absoluteURL else {
            throw ServerLedgerAPIClientError.invalidURL
        }

        let token = tokenProvider()
        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = method
        urlRequest.setValue("application/json", forHTTPHeaderField: "Accept")
        urlRequest.setValue(
            ServerLedgerContract.clientValue,
            forHTTPHeaderField: ServerLedgerContract.clientContractHeader
        )
        urlRequest.setValue(
            ServerLedgerContract.clientValue,
            forHTTPHeaderField: ServerLedgerContract.clientCompatibilityHeader
        )
        if let token, token.isEmpty == false {
            urlRequest.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        }
        if let mutation {
            urlRequest.setValue(
                mutation.idempotencyKey,
                forHTTPHeaderField: ServerLedgerContract.idempotencyHeader
            )
            urlRequest.setValue(
                String(mutation.expectedRevision),
                forHTTPHeaderField: ServerLedgerContract.expectedRevisionHeader
            )
        }
        if let body {
            urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
            urlRequest.httpBody = body
        }

        do {
            let (data, response) = try await session.data(for: urlRequest)
            guard let httpResponse = response as? HTTPURLResponse else {
                throw ServerLedgerAPIClientError.invalidResponse
            }
            return (data, httpResponse.statusCode)
        } catch let error as ServerLedgerAPIClientError {
            throw error
        } catch let error as URLError {
            switch error.code {
            case .notConnectedToInternet, .networkConnectionLost, .cannotFindHost,
                 .cannotConnectToHost, .timedOut, .dnsLookupFailed:
                throw ServerLedgerAPIClientError.offline
            default:
                throw error
            }
        }
    }

    private func makeHTTPError(
        status: Int,
        data: Data,
        scope: ServerBackedLedgerScope?,
        expectedRevision: Int64?
    ) throws -> ServerLedgerAPIClientError {
        if status == 401 { return .unauthorized }
        if status == 409 {
            if let conflict = try? JSONDecoder.serverLedger.decode(
                ServerLedgerConflictEnvelopeDTO.self,
                from: data
            ) {
                let snapshot = try conflict.snapshot.flatMap { envelope -> ServerLedgerSnapshot? in
                    guard let scope else { return nil }
                    let payload = try JSONEncoder.serverLedger.encode(envelope)
                    return try? ServerLedgerDocumentValidator.snapshot(from: payload, scope: scope)
                }
                switch conflict.conflict.code {
                case "REVISION_CONFLICT":
                    return .revisionConflict(
                        expectedRevision: conflict.conflict.expectedRevision ?? expectedRevision ?? 0,
                        currentRevision: conflict.conflict.currentRevision ?? conflict.revision,
                        snapshot: snapshot
                    )
                case "IDEMPOTENCY_KEY_REUSED":
                    return .idempotencyKeyReused
                default:
                    break
                }
            }
            return .server(status: status, code: Self.errorCode(from: data))
        }
        return .server(status: status, code: Self.errorCode(from: data))
    }

    private static func errorCode(from data: Data) -> String? {
        guard let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { return nil }
        return object["error"] as? String
            ?? (object["code"] as? String)
            ?? ((object["conflict"] as? [String: Any])?["code"] as? String)
    }

    private static func readModelData(from data: Data) -> Data? {
        guard let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let readModel = object["readModel"] else { return nil }
        return try? JSONSerialization.data(withJSONObject: readModel)
    }

    private static func scope(from data: Data, accountID: String) -> ServerBackedLedgerScope? {
        guard let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }
        let scopeObject = object["scope"] as? [String: Any]
        let groupID = (scopeObject?["groupId"] as? String)
            ?? (object["groupId"] as? String)
        let responseAccountID = (scopeObject?["accountId"] as? String)
            ?? (object["accountId"] as? String)
            ?? accountID
        guard responseAccountID == accountID,
              let groupID,
              groupID.isEmpty == false else { return nil }
        return ServerBackedLedgerScope(accountID: accountID, groupID: groupID)
    }

    private static func pathComponent(_ value: String) -> String {
        let allowed = CharacterSet.urlPathAllowed.subtracting(CharacterSet(charactersIn: "/"))
        return value.addingPercentEncoding(withAllowedCharacters: allowed) ?? value
    }
}

typealias LiveServerLedgerAPIClient = URLSessionServerLedgerAPIClient
typealias ServerLedgerHTTPClient = URLSessionServerLedgerAPIClient

private enum ServerLedgerMutationRoute {
    static func defaultPath(for request: ServerLedgerMutationRequest) -> String? {
        guard case let .serverBacked(_, groupID) = request.scope else {
            return nil
        }
        let encodedGroup = groupID.addingPercentEncoding(
            withAllowedCharacters: CharacterSet.urlPathAllowed.subtracting(CharacterSet(charactersIn: "/"))
        ) ?? groupID
        let body = (try? JSONSerialization.jsonObject(with: request.bodyPayload)) as? [String: Any]
        let kind = request.kind.lowercased()
        if kind.hasPrefix("expense") {
            if kind.contains("delete") || kind.contains("edit") || kind.contains("update") {
                if let id = (body?["expenseId"] as? String) ?? (body?["id"] as? String) {
                    return "/api/mobile/expenses/\(id)"
                }
            }
            return "/api/mobile/expenses"
        }
        if kind.hasPrefix("membership") {
            return "/api/mobile/groups/\(encodedGroup)/members"
        }
        if kind.contains("finalize") {
            return "/api/mobile/groups/\(encodedGroup)/finalize"
        }
        if kind.hasPrefix("group") {
            return "/api/mobile/groups"
        }
        if kind.hasPrefix("settlement") || kind.hasPrefix("settings") {
            return "/api/groups/\(encodedGroup)/settlements"
        }
        return "/api/mobile/ledger/groups/\(encodedGroup)/mutations"
    }
}

private extension ServerLedgerMutationRequest {
    func bodyWithMetadata() -> Data {
        guard var object = (try? JSONSerialization.jsonObject(with: bodyPayload)) as? [String: Any] else {
            return bodyPayload
        }
        object["operationId"] = idempotencyKey
        if object["expectedRevision"] == nil {
            object["expectedRevision"] = expectedRevision
        }
        return (try? JSONSerialization.data(withJSONObject: object)) ?? bodyPayload
    }
}
